### PR TITLE
Support Gradle 2.5

### LINKED ISSUE #8: Build fails with Gradle 2.5
If a project is built with Gradle 2.5, the build will fail with the following exception:
```
Could not find method executeWithoutThrowingTaskFailure() for arguments [] on task ':aarLinkSources'
```

This is due to a change in Gradle 2.5 : https://github.com/gradle/gradle/commit/f58d618aa912955f01bee42bba828a3b9c3924b3

I already have an easy fix:
```groovy
try {
	aarLinkSourcesTask.execute()
} catch (e) {
	// maybe log?
}
```

However i think it would be even better to only execute this plugin if it is in tooling mode, eg. when called by the IDE. This is totally unnecessary when called from command line. I am waiting for [feedback](https://discuss.gradle.org/t/plugin-is-in-tooling-mode/10503) on that.

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #8.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
The patch is based on [this](https://github.com/xujiaao/AARLinkSources/issues/8) discussion.

**Comment by ckesc** [comment]
Good fix! @xujiaao please merge it!

**Comment by plackemacher** [comment]
+1

**Comment by jfmoy** [comment]
Should be merged, would be sad to have to have to use a fork.

**Comment by hzsweers** [comment]
@xujiaao what's the hold up here? Gradle 2.6 is out now, currently any projects using this are stuck with 2.4

**Comment by glureau** [comment]
Still stuck on 2.4, please @xujiaao

**Comment by hzsweers** [comment]
This library is no longer necessary, as sources attachment is now included in android studio as of 1.4 beta 3.

https://code.google.com/p/android/issues/detail?id=59220

**Comment by pcqpcq** [comment]
any way, as 1.4 is still in beta for now

**Pull request merged**
